server:
  port: ${PORT:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  application:
    name: AgencyConnectDashboard

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agencydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m

  # Nouvelle configuration Liquibase (utilise JDBC)
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agencydb}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    com.example.AgencyConnectDashboard: DEBUG