server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  application:
    name: AgencyConnectDashboard

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:yowyob}?schema=${DB_SCHEMA:ride_and_go}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  # Nouvelle configuration Liquibase (utilise JDBC)
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:yowyob}
    user: ${DB_LIQUIBASE_USERNAME}
    password: ${DB_LIQUIBASE_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${DB_SCHEMA:ride_and_go}
    liquibase-schema: ${DB_SCHEMA:ride_and_go}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    com.example.AgencyConnectDashboard: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
